#Owner clan has all permissions

#Dont enable tag and tab if you are using a plugin that changes the tablist
#Preffix aply to tab and tag, suffix only to tag
clan:
  limit: 10
chat_feature:
  enable: true
  global: '&7[&8{clan}&7]&r {player}&7: {message}'
  clan: "&aClan &7chat > &8{player}: &a{message}"
  ally:  "&bAlly &7chat > &8{player}: &b{message}"
permissions:
  officer:
    - INVITE
    - KICK
    - SET
    - DEMOTE
    - HOME
    - INVENTORY
    - DEPOSIT
    - WITHDRAW
    - BUY
    - WAR
    - ENEMY
    - ALLY
  member:
    - HOME
    - INVENTORY
    - DEPOSIT
  recruit:
    - NONE