
clan:
  limit: 10
  
chat_feature:
  enable: true #This only apply to global, clan and ally chat will be always enabled
  global: '&7[&8{clan}&7]&r {player}&7: '
  clan: "&aClan &7chat > &8{player}: &a{message}"
  ally:  "&bAlly &7chat > &8{player}: &b{message}"

#Owner clan has all permissions
permissions:
  officer:
    - INVITE
    - KICK
    - SET
    - DEMOTE
    - HOME
    - INVENTORY
    - DEPOSIT
    - WITHDRAW
    - BUY
    - WAR
    - ENEMY
    - ALLY
  member:
    - HOME
    - INVENTORY
    - DEPOSIT
  recruit:
    - NONE